import React, { useState } from 'react';
import { Link, useLocation, useNavigate } from 'react-router-dom';
import { AlertCircle, Loader2 } from 'lucide-react';
import { api } from '../../services/api';
import { validatePassword } from '../../utils/validation';

export default function ChangePassword() {
  const { state } = useLocation(); const navigate = useNavigate(); const [password, setPassword] = useState(''); const [confirm, setConfirm] = useState(''); const [error, setError] = useState(''); const [fieldError, setFieldError] = useState(''); const [busy, setBusy] = useState(false);
  if (!state?.resetToken) return <div className="text-center text-slate-600">Verify your code first from <Link to="/forgot-password" className="text-yellow-700 underline">Forgot password</Link>.</div>;
  const submit = async (event) => { event.preventDefault(); const passwordError = validatePassword(password); if (passwordError) { setFieldError(passwordError); return; } if (password !== confirm) { setFieldError('Passwords do not match.'); return; } setError(''); setFieldError(''); setBusy(true); try { await api('/auth/reset-password', { method: 'POST', body: JSON.stringify({ resetToken: state.resetToken, newPassword: password }) }); navigate('/login'); } catch (err) { setError(err.message); } finally { setBusy(false); } };
  return <div className="w-full text-slate-700"><div className="text-center mb-8"><h2 className="text-2xl font-bold tracking-widest text-[#3b3a36] mb-2 uppercase">Set new password</h2><p className="text-slate-500 text-sm">Choose a new password for your account.</p></div>{error && <div className="mb-5 flex gap-2 p-3 rounded-xl bg-rose-50 text-rose-600 text-sm"><AlertCircle className="h-5 w-5 shrink-0" />{error}</div>}<form onSubmit={submit} className="space-y-5"><label className="block text-sm font-semibold text-gray-600">New password<input required minLength="8" autoComplete="new-password" type="password" value={password} onChange={e => { setPassword(e.target.value); if (fieldError) setFieldError(''); }} className={`mt-2 w-full border rounded-lg py-3 px-4 focus:outline-none ${fieldError ? 'border-rose-400 bg-rose-50' : 'border-gray-200 focus:border-yellow-500'}`} /></label><label className="block text-sm font-semibold text-gray-600">Confirm new password<input required minLength="8" autoComplete="new-password" type="password" value={confirm} onChange={e => { setConfirm(e.target.value); if (fieldError) setFieldError(''); }} className={`mt-2 w-full border rounded-lg py-3 px-4 focus:outline-none ${fieldError ? 'border-rose-400 bg-rose-50' : 'border-gray-200 focus:border-yellow-500'}`} /></label>{fieldError && <p className="text-sm text-rose-600">{fieldError}</p>}<button disabled={busy} className="w-full py-3 bg-yellow-50 hover:bg-yellow-100 text-yellow-800 border border-yellow-250 font-bold rounded-xl flex justify-center">{busy ? <Loader2 className="h-5 w-5 animate-spin" /> : 'Change password'}</button></form></div>;
}
