import React, { useRef, useState } from 'react';
import { Link, useLocation, useNavigate } from 'react-router-dom';
import { AlertCircle, Loader2 } from 'lucide-react';
import { api } from '../../services/api';

export default function EmailVerification() {
  const { state } = useLocation(); const navigate = useNavigate(); const email = state?.email; const [code, setCode] = useState(['', '', '', '', '', '']); const [error, setError] = useState(''); const [busy, setBusy] = useState(false); const refs = useRef([]);
  if (!email) return <div className="text-center text-slate-600">Start with <Link to="/forgot-password" className="text-yellow-700 underline">Forgot password</Link>.</div>;
  const change = (index, value) => { const digit = value.replace(/\D/g, '').slice(-1); const next = [...code]; next[index] = digit; setCode(next); if (digit && index < 5) refs.current[index + 1]?.focus(); };
  const submit = async (event) => { event.preventDefault(); const otp = code.join(''); if (otp.length !== 6) return setError('Enter the six-digit code from your email.'); setError(''); setBusy(true); try { const { resetToken } = await api('/auth/verify-reset-otp', { method: 'POST', body: JSON.stringify({ email, otp }) }); navigate('/change-password', { state: { resetToken } }); } catch (err) { setError(err.message); } finally { setBusy(false); } };
  return <div className="w-full text-slate-700"><div className="text-center mb-8"><h2 className="text-2xl font-bold tracking-widest text-[#3b3a36] mb-2 uppercase">Check your email</h2><p className="text-slate-500 text-sm">Enter the code sent to <strong>{email}</strong>.</p></div>{error && <div className="mb-5 flex gap-2 p-3 rounded-xl bg-rose-50 text-rose-600 text-sm"><AlertCircle className="h-5 w-5 shrink-0" />{error}</div>}<form onSubmit={submit} className="space-y-6"><div className="flex justify-center gap-2">{code.map((digit, index) => <input key={index} ref={el => refs.current[index] = el} inputMode="numeric" autoComplete={index === 0 ? 'one-time-code' : 'off'} maxLength="1" value={digit} onChange={e => change(index, e.target.value)} onKeyDown={e => e.key === 'Backspace' && !digit && index > 0 && refs.current[index - 1]?.focus()} className="w-11 h-14 text-center text-xl font-bold border border-slate-200 rounded-xl focus:outline-none focus:border-yellow-500" />)}</div><button disabled={busy} className="w-full py-3 bg-yellow-50 hover:bg-yellow-100 text-yellow-800 border border-yellow-250 font-bold rounded-xl flex justify-center">{busy ? <Loader2 className="h-5 w-5 animate-spin" /> : 'Verify code'}</button></form></div>;
}
